string id                       # query identifier
---
byte STATUS_OK = 0              # call succeeded
byte STATUS_INVALID_ID = 1      # query identifier is invalid
byte STATUS_QUERY_FAILED = 2    # query failed

byte status                     # status as defined above
bool result                     # true, if at least one solution exists
string error                    # error message if command failed
