byte FORMAT_PROLOG=0            # query is in Prolog format
byte FORMAT_JSON=1              # query is in JSON format

byte MODE_BATCH=0               # generate all solutions immediately
byte MODE_INCREMENTAL=1         # generate single solutions incrementally

byte format                     # query format as defined above
byte mode                       # query mode as defined above
string query                    # query in the specified format
---
bool ok                         # true if call succeeded
string id                       # query identifier if call succeeded
string error                    # error message if call did not succeed
